"""order relationship add

Revision ID: 031c67b2e0f0
Revises: 47f043b00ee7
Create Date: 2025-04-20 22:07:47.166421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031c67b2e0f0'
down_revision: Union[str, None] = '47f043b00ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_ticker_fkey', 'order', 'instrument', ['ticker'], ['ticker'])
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_ticker_fkey', 'order', type_='foreignkey')
    # ### end Alembic commands ###
