"""CASCADEDELUPD

Revision ID: 0e8184ce35ba
Revises: 2a4a8d675a16
Create Date: 2025-06-12 21:43:37.465211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8184ce35ba'
down_revision: Union[str, None] = '2a4a8d675a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_user_id_fkey', 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key('balance_user_id_fkey', 'balance', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
