"""CASCADEDEL

Revision ID: 2a4a8d675a16
Revises: 698da92ee979
Create Date: 2025-06-12 20:32:22.063394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4a8d675a16'
down_revision: Union[str, None] = '698da92ee979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_ticker_fkey', 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.drop_constraint('order_ticker_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.drop_constraint('transaction_ticker_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_ticker_fkey', 'transaction', 'instrument', ['ticker'], ['ticker'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_ticker_fkey', 'order', 'instrument', ['ticker'], ['ticker'])
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key('balance_ticker_fkey', 'balance', 'instrument', ['ticker'], ['ticker'])
    # ### end Alembic commands ###
