"""order add

Revision ID: 47f043b00ee7
Revises: 45d565b0eb98
Create Date: 2025-04-20 21:36:55.916171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f043b00ee7'
down_revision: Union[str, None] = '45d565b0eb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('market', 'limit', name='ordertype'), nullable=False),
    sa.Column('status', sa.Enum('new', 'exec', 'part_exec', 'canclled', name='orderstatus'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.Enum('buy', 'sell', name='operationdirection'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('filled', sa.Integer(), nullable=True),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.CheckConstraint('qty >= 1', name='check_qty_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
