"""transaction upd

Revision ID: 5835a81af2b9
Revises: 4f6ee16547a0
Create Date: 2025-06-15 18:54:38.947276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5835a81af2b9'
down_revision: Union[str, None] = '4f6ee16547a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_ticker_fkey', 'transaction', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_ticker_fkey', 'transaction', 'instrument', ['ticker'], ['ticker'])
    # ### end Alembic commands ###
