"""Upgrade balance

Revision ID: 698da92ee979
Revises: f27f0374dd19
Create Date: 2025-06-07 19:16:04.164126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698da92ee979'
down_revision: Union[str, None] = 'f27f0374dd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('reserved', sa.Float(), nullable=False))
    op.alter_column('balance', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('balance', 'reserved')
    # ### end Alembic commands ###
