"""unique balance

Revision ID: 69f1f55533ef
Revises: 71d22959ae20
Create Date: 2025-06-13 13:40:38.083947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f1f55533ef'
down_revision: Union[str, None] = '71d22959ae20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_ticker', 'balance', ['user_id', 'ticker'])
    op.drop_constraint('balance_user_id_fkey', 'balance', type_='foreignkey')
    op.drop_constraint('balance_ticker_fkey', 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'balance', 'instrument', ['ticker'], ['ticker'])
    op.drop_constraint('transaction_ticker_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'instrument', ['ticker'], ['ticker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_ticker_fkey', 'transaction', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key('balance_ticker_fkey', 'balance', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.create_foreign_key('balance_user_id_fkey', 'balance', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_ticker', 'balance', type_='unique')
    # ### end Alembic commands ###
